services:
  venio:
    build: .
    container_name: venio-app
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - /opt/docker/venio-files:/opt/docker/venio-files
      - venio-uploads:/app/uploads

volumes:
  venio-uploads:
